export const TEST_IDS = {
  login: {
    form: "login-form",
    username: "login-username",
    password: "login-password",
    remember: "login-remember",
    submit: "login-submit",
    error: "login-error",
    totp: "login-totp",
  },
  shell: {
    sidebar: "app-sidebar",
    topbar: "app-topbar",
    logout: "app-logout",
    ticker: "app-ticker",
    navDashboard: "nav-dashboard",
    navOwnerControl: "nav-owner-control",
    navRoles: "nav-roles",
    navAI: "nav-ai",
    navBrokers: "nav-brokers",
    navPlugins: "nav-plugins",
    navSettings: "nav-settings",
    navProfile: "nav-profile",
    navLogs: "nav-logs",
    userMenu: "app-user-menu",
  },
  dashboard: {
    root: "dashboard-root",
    aiStatus: "dashboard-ai-status",
    brokerStatus: "dashboard-broker-status",
    systemStatus: "dashboard-system-status",
    recentLogs: "dashboard-recent-logs",
  },
  ownerControl: {
    root: "owner-control-root",
    tabOverview: "oc-tab-overview",
    tabModules: "oc-tab-modules",
    tabSchema: "oc-tab-schema",
    tabDev: "oc-tab-dev",
    tabApprovals: "oc-tab-approvals",
    devInput: "dev-ask-input",
    devSend: "dev-ask-send",
    devOutput: "dev-ask-output",
    approvalNew: "dev-approval-new",
  },
  ai: {
    root: "ai-root",
    healthBtn: "ai-health-btn",
    chatInput: "ai-chat-input",
    chatSend: "ai-chat-send",
    chatOutput: "ai-chat-output",
    providerCard: (id) => `ai-provider-${id}`,
    setDefault: (id) => `ai-set-default-${id}`,
    presetsList: "ai-presets-list",
    presetNewName: "ai-preset-new-name",
    presetNewPrompt: "ai-preset-new-prompt",
    presetCreate: "ai-preset-create",
    presetRun: (id) => `ai-preset-run-${id}`,
    presetDelete: (id) => `ai-preset-delete-${id}`,
  },
  brokers: {
    root: "brokers-root",
    pluginsList: "brokers-plugins-list",
    accountsList: "brokers-accounts-list",
    emptyPlugins: "brokers-empty-plugins",
    addBtn: (id) => `brokers-add-${id}`,
    modal: "brokers-modal",
    modalPlugin: "brokers-modal-plugin",
    modalLabel: "brokers-modal-label",
    modalCred: (k) => `brokers-modal-cred-${k}`,
    modalSubmit: "brokers-modal-submit",
    connect: (id) => `brokers-connect-${id}`,
    disconnect: (id) => `brokers-disconnect-${id}`,
    remove: (id) => `brokers-remove-${id}`,
    primary: (id) => `brokers-primary-${id}`,
  },
  plugins: {
    root: "plugins-root",
    empty: "plugins-empty",
  },
  settings: {
    root: "settings-root",
    tabSystem: "settings-tab-system",
    tabSecurity: "settings-tab-security",
    tabAppearance: "settings-tab-appearance",
    tabNotifications: "settings-tab-notifications",
    save: "settings-save",
  },
  profile: {
    root: "profile-root",
    displayName: "profile-display-name",
    save: "profile-save",
    changePwCurrent: "profile-pw-current",
    changePwNew: "profile-pw-new",
    changePwSubmit: "profile-pw-submit",
    sessions: "profile-sessions",
    logoutAll: "profile-logout-all",
    twoFA: "profile-2fa",
    twoFAEnable: "profile-2fa-enable",
    twoFAVerify: "profile-2fa-verify",
    twoFACode: "profile-2fa-code",
    twoFADisable: "profile-2fa-disable",
    trustedDevices: "profile-trusted-devices",
  },
  roles: {
    root: "roles-root",
  },
  logs: {
    root: "logs-root",
    search: "logs-search",
    filterLevel: "logs-filter-level",
    filterCategory: "logs-filter-category",
  },
};
