export const TEST_IDS = {
  login: {
    form: "login-form",
    username: "login-username",
    password: "login-password",
    remember: "login-remember",
    submit: "login-submit",
    error: "login-error",
  },
  shell: {
    sidebar: "app-sidebar",
    topbar: "app-topbar",
    logout: "app-logout",
    navDashboard: "nav-dashboard",
    navAI: "nav-ai",
    navBrokers: "nav-brokers",
    navPlugins: "nav-plugins",
    navSettings: "nav-settings",
    navProfile: "nav-profile",
    navRoles: "nav-roles",
    navLogs: "nav-logs",
    userMenu: "app-user-menu",
  },
  dashboard: {
    root: "dashboard-root",
    aiStatus: "dashboard-ai-status",
    brokerStatus: "dashboard-broker-status",
    systemStatus: "dashboard-system-status",
    recentLogs: "dashboard-recent-logs",
  },
  ai: {
    root: "ai-root",
    healthBtn: "ai-health-btn",
    chatInput: "ai-chat-input",
    chatSend: "ai-chat-send",
    chatOutput: "ai-chat-output",
    providerCard: (id) => `ai-provider-${id}`,
    setDefault: (id) => `ai-set-default-${id}`,
  },
  brokers: {
    root: "brokers-root",
    pluginsList: "brokers-plugins-list",
    accountsList: "brokers-accounts-list",
    emptyPlugins: "brokers-empty-plugins",
  },
  plugins: {
    root: "plugins-root",
    empty: "plugins-empty",
  },
  settings: {
    root: "settings-root",
    tabSystem: "settings-tab-system",
    tabSecurity: "settings-tab-security",
    tabAppearance: "settings-tab-appearance",
    tabNotifications: "settings-tab-notifications",
    save: "settings-save",
  },
  profile: {
    root: "profile-root",
    displayName: "profile-display-name",
    save: "profile-save",
    changePwCurrent: "profile-pw-current",
    changePwNew: "profile-pw-new",
    changePwSubmit: "profile-pw-submit",
    sessions: "profile-sessions",
    logoutAll: "profile-logout-all",
  },
  roles: {
    root: "roles-root",
  },
  logs: {
    root: "logs-root",
    search: "logs-search",
    filterLevel: "logs-filter-level",
    filterCategory: "logs-filter-category",
  },
};
